stages:
  - build
  - deploy

.build template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:${registry_ref}

build development:
  extends: .build template
  only:
    - development
  variables:
    registry_ref: staging

build master:
  extends: .build template
  only:
    - master
  variables:
    registry_ref: latest

production deployment:
  stage: deploy
  only:
    - master
  image: alpine/helm
  environment:
    name: production
  script:
    - helm version
    - |
      helm upgrade -n flottenportal --install customer-portal-app ./helm-chart \
        --set deployment.apiUrl="$API_URL" \
        --set deployment.apiBaseUrl="$API_BASE_URL" \
        --wait
